service: usrv-notification

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-dynamodb-local

functions:
  dynamoDBStreamHandler:
    handler: handler.dynamoDBStreamHandler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:123456789012:table/usrv-payments/stream/LATEST
          batchSize: 100
          startingPosition: LATEST
